---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: demo-keda-trigger-auth
  namespace: demo-keda
spec:
  secretTargetRef:
    - parameter: host
      name: demo-keda-secret
      key: host
