---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-keda-scaledobject
  namespace: demo-keda
spec:
  scaleTargetRef:
    name: httpbin
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: test_q
      mode: QueueLength
      value: "100"
    authenticationRef:
      name: demo-keda-trigger-auth
